(function () {
  'use strict';
  const engine = window.GasGuardEngine, data = window.GasGuardData, providers = window.GasGuardProviders;
  const $ = id => document.getElementById(id);
  const VIEW_KEY = 'gasguard-v2-view-mode';
  const escape = v => String(v).replace(/[&<>"']/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[c]));
  const statusText = s => ({ safe:'ปกติ', attention:'เฝ้าระวัง', critical:'เสี่ยงสูง', unknown:'ไม่ทราบสถานะ' }[s]);
  const statusClass = s => s === 'critical' ? 'danger' : s;
  const fmt = n => n == null ? '—' : new Intl.NumberFormat('th-TH').format(n);
  const time = t => new Intl.DateTimeFormat('th-TH',{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(t);
  const replayFrames = [
    {time:'10:05:00',title:'Baseline stable',state:'safe',ppm:84,rate:'0.2 ppm/min',risk:'8/100',copy:'LPG อยู่ใกล้ baseline และบริบทการใช้งานปกติ จึงไม่มีหลักฐานความเสี่ยงเร่งด่วน'},
    {time:'10:05:30',title:'Unexpected increase begins',state:'attention',ppm:170,rate:'+4.1 ppm/min',risk:'37/100',copy:'ค่า LPG เริ่มเพิ่มเร็วกว่า pattern เดิม ขณะที่ valve รายงานปิด จึงเริ่มต้องติดตามหลักฐานต่อเนื่อง'},
    {time:'10:06:00',title:'Multi-factor anomaly detected',state:'critical',ppm:390,rate:'+9.6 ppm/min',risk:'74/100',copy:'ความเข้มข้น อัตราเพิ่ม และความต่างจาก baseline สนับสนุนกัน ระบบจึงยกระดับเป็นเหตุการณ์เสี่ยงสูง'},
    {time:'10:06:30',title:'Critical evidence confirmed',state:'critical',ppm:710,rate:'+13.4 ppm/min',risk:'94/100',copy:'LPG เพิ่มต่อเนื่องแม้รายงาน valve ปิด เป็นเหตุการณ์ที่ต้องตรวจสอบหน้างานและยืนยันระบบจริงทันที'}
  ];
  let replayIndex = 0;
  let latestValidationRun = null, latestFailSafeRun = null;

  function metric(label, value, detail, icon) { return `<article class="metric"><div class="metric-label"><span class="metric-icon" aria-hidden="true">${icon}</span>${label}</div><div class="metric-value">${value}</div><div class="metric-detail">${detail}</div></article>`; }
  function lineChart(id, readings, baseline) {
    const svg = $(id), values = readings.map(r => r.gas.value), w = id === 'live-chart' ? 920 : 720, h = id === 'live-chart' ? 260 : 210, pad = 18, min = Math.max(0, Math.min(...values, baseline) - 25), max = Math.max(...values, baseline + 40);
    const x = i => pad + i * (w - pad * 2) / Math.max(1, values.length - 1), y = v => h - pad - ((v - min) / Math.max(1,max - min)) * (h - pad * 2);
    const points = values.map((v,i) => `${x(i)},${y(v)}`).join(' ');
    const grid = [0.2,.5,.8].map(f => `<line class="chart-grid" x1="${pad}" x2="${w-pad}" y1="${pad+(h-pad*2)*f}" y2="${pad+(h-pad*2)*f}"/>`).join('');
    svg.innerHTML = `${grid}<line class="chart-baseline" x1="${pad}" x2="${w-pad}" y1="${y(baseline)}" y2="${y(baseline)}"/><polyline class="chart-line" points="${points}"/><circle class="chart-dot" cx="${x(values.length-1)}" cy="${y(values.at(-1))}" r="4"/>`;
  }
  function renderOverview(f, d) {
    $('safety-state').textContent = f.safety === 'unknown' ? 'ไม่สามารถยืนยันความปลอดภัย' : `${statusText(f.safety)} · Kitchen A`;
    $('safety-message').textContent = d.text;
    $('safety-score').textContent = f.risk == null ? '—' : 100 - f.risk;
    $('safety-score-caption').textContent = f.risk == null ? 'Monitoring unavailable' : `${statusText(f.safety)} safety state`;
    $('safety-hero').style.background = f.safety === 'critical' ? 'oklch(.37 .13 28)' : f.safety === 'unknown' ? 'oklch(.31 .03 258)' : 'var(--ink)';
    $('overview-metrics').innerHTML = [metric('LPG ปัจจุบัน',`${fmt(f.current.gas.value)} ppm`,`Baseline ${fmt(f.baseline)} ppm`,'⌁'),metric('อัตราการเพิ่ม',`${f.rate > 0 ? '+' : ''}${f.rate} ppm/min`,f.rate > 3 ? 'เพิ่มขึ้นต่อเนื่อง' : 'แนวโน้มคงที่','↗'),metric('Sensor confidence',`${f.confidence}%`,f.confidence > 80 ? 'คุณภาพข้อมูลดี' : 'ตรวจบริบทแวดล้อม','◌'),metric('Valve / connection',`${f.current.system.valve === 'unknown' ? '—' : f.current.system.valve.toUpperCase()}`,f.current.system.connection === 'online' ? 'Monitoring online' : 'Monitoring unavailable','⌘')].join('');
    lineChart('overview-chart',engine.state.readings.slice(-20),f.baseline); $('baseline-value').textContent = `${f.baseline} ppm`; $('rate-value').textContent = `${f.rate > 0 ? '+' : ''}${f.rate} ppm/min`;
    $('trend-status').className = `status-pill ${statusClass(f.safety)}`; $('trend-status').textContent = statusText(f.safety); $('insight-title').textContent = d.title; $('insight-body').textContent = d.text;
    const guide = f.safety === 'unknown' ? ['ตรวจสอบการติดตามก่อน', 'เซ็นเซอร์หรือเครือข่ายไม่ส่งข้อมูลใหม่ จึงยังยืนยันความปลอดภัยไม่ได้'] : f.safety === 'critical' ? ['ตรวจพื้นที่และยืนยันสาเหตุ', 'มีหลักฐานหลายส่วนที่บ่งชี้ความเสี่ยงสูง โปรดดู Alert Center และตรวจระบบหน้างาน'] : f.safety === 'attention' ? ['ติดตามแนวโน้มอีกระยะ', 'ค่ากำลังเปลี่ยนจาก pattern ปกติ ตรวจสอบว่าครัวกำลังใช้งานตามคาดหรือไม่'] : ['การติดตามอยู่ในเกณฑ์ปกติ', 'ไม่มี action เร่งด่วน ดู trend และ alert ได้เมื่อจำเป็น'];
    $('action-guide-title').textContent=guide[0]; $('action-guide-copy').textContent=guide[1];
  }
  function renderLive(f) {
    $('live-updated').textContent = `อัปเดตล่าสุด ${time(new Date(f.current.timestamp))} · ${f.current.system.connection}`; $('live-status').className = `status-pill ${statusClass(f.safety)}`; $('live-status').textContent = statusText(f.safety); $('live-ppm').textContent = fmt(f.current.gas.value); $('live-trend-copy').textContent = f.safety === 'unknown' ? 'ข้อมูลล่าสุดไม่เพียงพอสำหรับการประเมิน' : `Rate of rise ${f.rate > 0 ? '+' : ''}${f.rate} ppm/min · ${f.rate > 3 ? 'increasing' : 'stable'}`;
    lineChart('live-chart',engine.state.readings.slice(-60),f.baseline); $('live-metrics').innerHTML = [metric('Baseline',`${f.baseline} ppm`,'Rolling historical mean','◌'),metric('Temperature',`${f.current.environment.temperature}°C`,'Environmental context','◒'),metric('Humidity',`${f.current.environment.humidity}%`,'Confidence adjustment','◑'),metric('Valve',f.current.system.valve.toUpperCase(),'Actuator context','⌘'),metric('Battery',`${f.current.system.battery}%`,'Gateway backup','▰'),metric('Signal',`${f.current.system.rssi} dBm`,'Connection health','⌁')].join('');
    const pairs = [['Raw reading',`${f.current.gas.rawValue} ADC-equivalent`],['Calibrated LPG',`${f.current.gas.value} ppm`],['Rolling variance',`${f.variance} ppm`],['Z deviation',f.z],['30 min exposure',`${fmt(f.exposure)} ppm·min`],['Calibration',f.current.gas.calibrationVersion]];
    $('feature-trace').innerHTML = pairs.map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('');
  }
  function renderIntelligence(f,d) {
    $('risk-heading').textContent = f.risk == null ? 'Safety state unknown' : `${statusText(f.safety)} risk assessment`; $('risk-summary').textContent = f.risk == null ? 'ไม่มีข้อมูลจากเซ็นเซอร์ จึงไม่สร้าง risk score ที่อาจทำให้เข้าใจผิด' : `Rule-based model v0.1 ประเมินจาก concentration, rate, exposure, anomaly, valve และ confidence`;
    $('risk-score').textContent = f.risk == null ? '—' : f.risk; $('risk-ring').style.borderTopColor = f.safety === 'critical' ? 'var(--danger)' : f.safety === 'attention' ? 'var(--attention)' : f.safety === 'unknown' ? 'var(--unknown)' : 'var(--success)';
    const reasons = [['Gas concentration',`${f.current.gas.value} ppm`,f.current.gas.value > f.baseline + 55 ? 'สูงกว่า baseline อย่างมีนัยสำคัญ' : 'อยู่ใกล้ baseline'],['Rate of rise',`${f.rate > 0 ? '+' : ''}${f.rate} ppm/min`,f.rate > 3 ? 'การเพิ่มต่อเนื่องเพิ่มความเสี่ยง' : 'ไม่มีแนวโน้มเพิ่มเร็ว'],['Exposure',`${fmt(f.exposure)} ppm·min`,f.exposure > 1200 ? 'ระดับสูงสะสมในช่วง 30 นาที' : 'การสะสมต่ำ'],['Historical anomaly',`${f.anomaly}/100`,f.anomaly > 50 ? 'แตกต่างจาก pattern ปกติ' : 'ใกล้เคียงพฤติกรรมปกติ'],['Sensor confidence',`${f.confidence}%`,f.confidence > 80 ? 'ข้อมูลใช้ประกอบการตัดสินใจได้' : 'ปรับลดความเชื่อมั่นจากบริบท'],['Valve & connection',`${f.current.system.valve} · ${f.current.system.connection}`,f.current.system.connection === 'online' ? 'สถานะ telemetry พร้อมใช้' : 'ไม่อนุมานว่า safe เมื่อ offline']];
    $('reason-grid').innerHTML = reasons.map(r=>`<article class="reason"><span class="reason-label">${r[0]}</span><strong>${r[1]}</strong><p>${r[2]}</p></article>`).join(''); $('explanation-title').textContent=d.title; $('explanation-body').textContent=d.text; $('recommendation').textContent=`คำแนะนำ: ${d.action}`;
  }
  function renderAnalytics(f) {
    const vals=engine.state.readings.slice(-120).map(r=>r.gas.value), above=vals.filter(v=>v>f.baseline).length*2;
    $('analytics-metrics').innerHTML=[metric('ค่าเฉลี่ย 4 ชั่วโมง',`${fmt(Math.round(vals.reduce((a,b)=>a+b,0)/vals.length))} ppm`,'Historical mock dataset','◌'),metric('ค่าสูงสุด',`${fmt(Math.max(...vals))} ppm`,'Peak reading','↑'),metric('เหนือ baseline',`${above} min`,'Time above historical mean','◷'),metric('Anomaly ปัจจุบัน',`${f.anomaly}/100`,'Deviation model','✦')].join('');
    const days=['จ','อ','พ','พฤ','ศ','ส','อา']; let html='<div class="heatmap-cell label"></div>'+days.map(d=>`<div class="heatmap-cell label">${d}</div>`).join(''); data.dailyPattern.forEach(row=>{html+=`<div class="heatmap-cell label">${row[0]}</div>`+row.slice(1).map(v=>`<div class="heatmap-cell ${v>160?'level-3':v>110?'level-2':'level-1'}">${v}</div>`).join('')}); $('heatmap').innerHTML=html;
    const events=engine.state.events.filter(e=>e.type!=='system').slice(0,4); $('anomaly-list').innerHTML=events.length?events.map(e=>`<div class="anomaly-row"><div><strong>${escape(e.title)}</strong><span>${escape(e.detail)}</span></div><span>${time(e.t)}</span></div>`).join(''):'<p>ยังไม่มีเหตุการณ์ผิดปกติในสถานการณ์จำลองนี้</p>';
  }
  function renderEvents(){ $('event-list').innerHTML=engine.state.events.map(e=>`<article class="event ${e.type}"><time>${time(e.t)}</time><span class="event-marker" aria-hidden="true"></span><div><h3>${escape(e.title)}</h3><p>${escape(e.detail)}</p></div></article>`).join(''); }
  function renderDevices(f){const devices=[['ESP32 Gateway','GG-GW-01','online','98%','-58 dBm'],['LPG Sensor','LPG-01',f.current.system.connection,`${f.sensorHealth}%`,`${f.current.gas.value} ppm`],['Temp / RH Sensor','ENV-01','online','96%',`${f.current.environment.temperature}°C · ${f.current.environment.humidity}%`],['Valve Controller','VALVE-01',f.current.system.valve==='unknown'?'unknown':'online','99%',f.current.system.valve.toUpperCase()]];$('device-list').innerHTML=devices.map(d=>`<article class="device"><div><h3>${d[0]}</h3><p>${d[1]} · Kitchen A</p></div><div class="device-metric"><span>สถานะ</span><strong>${d[2]}</strong></div><div class="device-metric"><span>Health</span><strong>${d[3]}</strong></div><div class="device-metric"><span>ล่าสุด</span><strong>${d[4]}</strong></div></article>`).join('');}
  function renderMaintenance(f){const health=f.sensorHealth;$('maintenance-metrics').innerHTML=[metric('Sensor health',`${health}%`,health>80?'พร้อมใช้งาน':'ควรวางแผนตรวจสอบ','◌'),metric('Baseline drift',`${f.drift>0?'+':''}${f.drift} ppm`,'เทียบ reference baseline 84 ppm','↗'),metric('Data confidence',`${f.confidence}%`,'Temperature/RH adjusted','◒'),metric('Connection health',f.current.system.connection==='online'?'Online':'Offline',`${f.current.system.rssi} dBm · battery ${f.current.system.battery}%`,'⌁')].join('');$('health-heading').textContent=health>85?'Sensor health is good':health>65?'Sensor health needs observation':'Sensor inspection recommended';$('health-copy').textContent=`ค่า baseline เปลี่ยน ${f.drift>0?'+':''}${f.drift} ppm จาก reference และข้อมูลปัจจุบันมี confidence ${f.confidence}%`; $('health-bar').style.width=`${health}%`; $('health-bar').style.background=health>85?'var(--success)':health>65?'var(--attention)':'var(--danger)';$('health-trace').innerHTML=[['Baseline drift',`${f.drift>0?'+':''}${f.drift} ppm`],['Variance',`${f.variance} ppm`],['Last calibration','12 Aug 2026'],['Next review','12 Nov 2026'],['Gateway battery',`${f.current.system.battery}%`],['Packet state',f.current.system.connection]].map(x=>`<div><dt>${x[0]}</dt><dd>${x[1]}</dd></div>`).join('');const plan=[['ตรวจสอบ calibration ตามรอบ','กำหนดตรวจ sensor response ทุก 90 วัน'],['ติดตาม baseline drift','แจ้งวิศวกรเมื่อ baseline เบี่ยงเกินเกณฑ์ที่ validate แล้ว'],['ทดสอบ valve feedback','บันทึก open/closed feedback ทุกครั้งที่มี command']];$('maintenance-list').innerHTML=plan.map(x=>`<div class="maintenance-item"><strong>${x[0]}</strong><p>${x[1]}</p></div>`).join('');}
  function answerQuery(kind){const f=engine.analysis, recent=engine.state.events.find(e=>e.type!=='system');let h,p;if(kind==='risk'){h=f.risk==null?'ยังไม่มี risk score':'Risk score เปลี่ยนจากหลักฐานหลายส่วน';p=f.risk==null?'เซ็นเซอร์ offline จึงไม่คำนวณ risk score เพื่อหลีกเลี่ยงข้อสรุปที่ผิดพลาด.':`Risk ปัจจุบัน ${f.risk}/100 มาจาก LPG ${f.current.gas.value} ppm เทียบ baseline ${f.baseline} ppm, rate ${f.rate} ppm/min, exposure ${f.exposure} ppm·min และ anomaly ${f.anomaly}/100. Confidence ของข้อมูลคือ ${f.confidence}%.`;}else if(kind==='events'){h=recent?recent.title:'ยังไม่มีเหตุการณ์ผิดปกติ';p=recent?`${recent.detail} เหตุการณ์นี้ถูกเก็บใน Event Timeline เพื่อให้ตรวจสอบย้อนหลังได้.`:'ข้อมูลล่าสุดยังอยู่ใน pattern ที่คาดหมาย และไม่มี safety event ใหม่ในสถานการณ์จำลองนี้.';}else if(kind==='health'){h=`Sensor health ${f.sensorHealth}%`;p=`Baseline drift ${f.drift>0?'+':''}${f.drift} ppm, variance ${f.variance} ppm และ confidence ${f.confidence}% ถูกใช้ประเมินความพร้อมของเซ็นเซอร์. ${f.sensorHealth>85?'ยังไม่มีสัญญาณที่ต้องสอบเทียบทันที.':'ควรวางแผนตรวจสอบ calibration ตามรอบ.'}`;}else{h='รูปแบบ LPG ในข้อมูลจำลอง';p='ช่วง 08:00–20:00 มีค่าเฉลี่ยสูงกว่าช่วงกลางคืน โดยเฉพาะวันสุดสัปดาห์. Analytics หน้า Historical แสดง heatmap เพื่อให้ผู้ดูแลเปรียบเทียบ pattern กับเหตุการณ์จริงเมื่อเริ่มเก็บข้อมูลภาคสนาม.';}$('assistant-answer').innerHTML=`<p class="section-label">GASGUARD ANSWER</p><h2>${escape(h)}</h2><p>${escape(p)}</p>`;}
  function renderOperations(f){const alerts=engine.state.events.filter(e=>e.type==='warning'||e.type==='critical');$('alert-metrics').innerHTML=[metric('Open alerts',alerts.length,'จาก event timeline ปัจจุบัน','!'),metric('Current risk',f.risk==null?'Unknown':`${f.risk}/100`,statusText(f.safety),'✦'),metric('Highest severity',alerts.some(e=>e.type==='critical')?'Critical':alerts.length?'Warning':'None','Rule classification','↑'),metric('Monitoring',f.current.system.connection,'ล่าสุดจาก sensor','⌁')].join('');$('alert-list').innerHTML=alerts.length?alerts.map(e=>`<article class="event ${e.type}"><time>${time(e.t)}</time><span class="event-marker" aria-hidden="true"></span><div><h3>${escape(e.title)}</h3><p>${escape(e.detail)}</p></div></article>`).join(''):'<p>ไม่มี alert ในสถานการณ์จำลองปัจจุบัน</p>';const vals=engine.state.readings.map(r=>r.gas.value);$('report-summary').innerHTML=[['Readings retained',vals.length,'persistent local history'],['Events retained',engine.state.events.length,'audit timeline'],['LPG average',`${Math.round(vals.reduce((a,b)=>a+b,0)/vals.length)} ppm`,'current retained data']].map(x=>`<article class="report-item"><strong>${x[0]}</strong><span>${x[1]} · ${x[2]}</span></article>`).join('');const s=engine.state.source;$('source-mode').value=s.mode;$('rest-url').value=s.restUrl;$('mqtt-url').value=s.mqttUrl;$('mqtt-topic').value=s.topic;const note=$('source-status');const configured=s.mode==='simulation'||(s.mode==='rest'&&s.restUrl)||(s.mode==='mqtt'&&s.mqttUrl);note.textContent=configured?`สถานะปัจจุบัน: ${providers.message}`:`ยังตั้งค่า ${s.mode.toUpperCase()} ไม่ครบ, ระบบจะไม่ตีความว่าเชื่อมต่อสำเร็จ`;note.className=`form-note ${configured?'source-ok':'source-error'}`;}
  function renderDeveloper(f){const current=f.current,analysis={baseline:f.baseline,ratePpmPerMinute:f.rate,variance:f.variance,exposurePpmMinute:f.exposure,confidence:f.confidence,baselineDrift:f.drift,sensorHealth:f.sensorHealth,anomalyScore:f.anomaly,riskScore:f.risk,safetyState:f.safety,eventClassification:f.classification};$('developer-metrics').innerHTML=[metric('LPG',`${current.gas.value} ppm`,'calibrated reading','⌁'),metric('Raw value',current.gas.rawValue,'raw sensor input','▦'),metric('Timestamp',time(new Date(current.timestamp)),'latest payload','◷'),metric('Source',engine.state.source.mode,providers.status,'⌁'),metric('Retained readings',engine.state.readings.length,'local browser store','▤'),metric('Retained events',engine.state.events.length,'audit trail','!')].join('');$('reading-json').textContent=JSON.stringify(current,null,2);$('analysis-json').textContent=JSON.stringify(analysis,null,2);$('provider-state').innerHTML=[['Provider status',providers.status],['Provider message',providers.message],['Scenario',engine.state.scenario],['REST URL',engine.state.source.restUrl||'not configured'],['MQTT URL',engine.state.source.mqttUrl||'not configured'],['MQTT topic',engine.state.source.topic||'not configured']].map(x=>`<div><dt>${x[0]}</dt><dd>${escape(x[1])}</dd></div>`).join('');$('developer-events').innerHTML=engine.state.events.slice(0,10).map(e=>`<div class="developer-event"><strong>${escape(e.title)}</strong><span>${time(e.t)} · ${escape(e.type)} · ${escape(e.detail)}</span></div>`).join('');}
  function renderReplay(){const r=replayFrames[replayIndex];$('replay-steps').innerHTML=replayFrames.map((x,i)=>`<button class="replay-step ${i===replayIndex?'is-selected':''}" data-replay="${i}" type="button"><time>${x.time}</time><span><strong>${x.title}</strong><span>${statusText(x.state)}</span></span></button>`).join('');$('replay-time').textContent=r.time;$('replay-title').textContent=r.title;$('replay-copy').textContent=r.copy;$('replay-metrics').innerHTML=[['LPG',`${r.ppm} ppm`],['Rate',r.rate],['Risk',r.risk]].map(x=>`<div><strong>${x[1]}</strong><span>${x[0]}</span></div>`).join('');document.querySelectorAll('[data-replay]').forEach(b=>b.addEventListener('click',()=>{replayIndex=Number(b.dataset.replay);renderReplay()}));}
  function renderValidation(){const cases=engine.validation,current=engine.analysis,legacy=current.current.system.connection!=='online'?'unknown':current.current.gas.value>=300?'critical':current.current.gas.value>=180?'attention':'safe';const differs=legacy!==current.safety;$('validation-verdict').textContent=differs?'Contextual model ให้ผลต่างจาก threshold คงที่':'สองโมเดลให้ระดับเดียวกันใน reading นี้';$('validation-copy').textContent=differs?`Reading ปัจจุบัน ${current.current.gas.value} ppm, แต่ contextual model ใช้ baseline, rate, exposure, valve และ confidence ร่วมในการอธิบายระดับ ${statusText(current.safety)}.`:`Reading ปัจจุบัน ${current.current.gas.value} ppm ยังมีหลักฐานจากทั้งสองวิธีไปในทิศทางเดียวกัน. ทดลองเปลี่ยนสถานการณ์เพื่อดูความต่าง.`;$('validation-current').innerHTML=[['Contextual state',statusText(current.safety)],['Fixed threshold',statusText(legacy)],['Evidence factors','6 factors']].map(x=>`<div><dt>${x[0]}</dt><dd>${x[1]}</dd></div>`).join('');const result=$('test-result');if(latestValidationRun){result.innerHTML=`<strong>Scenario Test Runner: ${latestValidationRun.passed}/${latestValidationRun.total} ผ่าน</strong><span>รันเมื่อ ${time(new Date(latestValidationRun.ranAt))} · deterministic mock cases</span>`;}else result.innerHTML='<strong>ยังไม่ได้รันชุดทดสอบใน session นี้</strong><span>การแสดงผลเริ่มต้นมาจาก deterministic mock cases</span>';$('validation-list').innerHTML=cases.map(x=>{const contextual=x.contextualStep<0?'ไม่ยกระดับ':`step ${x.contextualStep+1}`;const threshold=x.thresholdStep<0?'ไม่ยกระดับ':`step ${x.thresholdStep+1}`;return `<article class="validation-case"><header><div><h3>${escape(x.title)}</h3><p>${escape(x.context)}</p></div><span class="status-pill ${x.pass?'safe':'danger'}">${x.pass?'ผ่าน mock expectation':'ตรวจทาน'}</span></header><p>${escape(x.note)}</p><div class="validation-result"><div><span>Contextual model</span><strong>${statusText(x.contextual)} · ${contextual}</strong></div><div><span>Fixed threshold</span><strong>${statusText(x.threshold)} · ${threshold}</strong></div></div></article>`}).join('');const checks=latestFailSafeRun?latestFailSafeRun.checks:[];$('failsafe-list').innerHTML=checks.length?checks.map(x=>`<div class="failsafe-item ${x.result==='PASS'?'pass':''}"><span>${escape(x.title)}</span><strong>${escape(x.result)}</strong><span>${escape(x.detail)}</span></div>`).join(''):'<div class="failsafe-item"><span>ยังไม่ได้รัน Fail-safe Drill</span><strong>รอการทดสอบ</strong><span>ผลจะตรวจ telemetry disconnect, malformed payload และขอบเขต remote actuation</span></div>';}
  function render(){const f=engine.analysis,d=engine.explanation; renderOverview(f,d);renderLive(f);renderIntelligence(f,d);renderReplay();renderValidation();renderAnalytics(f);renderEvents();renderDevices(f);renderMaintenance(f);renderOperations(f);renderDeveloper(f);const online=providers.status==='simulation'||providers.status==='online';$('connection-dot').style.background=online?'var(--success)':providers.status==='connecting'?'var(--attention)':'var(--unknown)';$('connection-label').textContent=providers.message;$('pause-button').textContent=engine.state.paused?'เริ่มข้อมูล':'พักข้อมูล';}
  function toast(title,detail,type){const el=document.createElement('div');el.className=`toast ${type||''}`;el.innerHTML=`<strong>${escape(title)}</strong><span>${escape(detail)}</span>`;$('toast-region').append(el);setTimeout(()=>el.remove(),5000)}
  function applyViewMode(mode){document.body.classList.toggle('owner-mode',mode==='owner');$('view-mode').value=mode;try{localStorage.setItem(VIEW_KEY,mode)}catch(e){}if(mode==='owner'&&document.querySelector('.nav-item.is-active.engineer-item'))document.querySelector('[data-page="overview"]').click();}
  document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('is-active'));b.classList.add('is-active');const page=b.dataset.page;document.querySelectorAll('.page').forEach(x=>x.classList.toggle('is-visible',x.id===`page-${page}`));const titles={overview:['SAFETY OVERVIEW','ภาพรวมความปลอดภัย'],live:['LIVE MONITOR','ตรวจวัดแบบสด'],intelligence:['SAFETY INTELLIGENCE','วิเคราะห์ความปลอดภัย'],replay:['SAFETY REPLAY','ย้อนดูหลักฐานความเสี่ยง'],validation:['VALIDATION LAB','ห้องทดลองการประเมิน'],analytics:['ANALYTICS','การวิเคราะห์ข้อมูล'],events:['EVENT TIMELINE','เหตุการณ์'],alerts:['ALERT CENTER','การแจ้งเตือน'],guide:['DATA & FUNCTION GUIDE','คู่มือข้อมูล'],devices:['DEVICE INVENTORY','อุปกรณ์'],maintenance:['MAINTENANCE','การบำรุงรักษา'],assistant:['ASK GASGUARD','ถามข้อมูลระบบ'],locations:['LOCATION HIERARCHY','สถานที่และโซน'],reports:['REPORTING','รายงาน'],settings:['SETTINGS','ตั้งค่า'],developer:['DEVELOPER CONSOLE','Developer Console']};$('page-kicker').textContent=titles[page][0];$('page-title').textContent=titles[page][1]}));
  document.querySelectorAll('[data-goto]').forEach(b=>b.addEventListener('click',()=>document.querySelector(`[data-page="${b.dataset.goto}"]`).click())); document.querySelectorAll('[data-query]').forEach(b=>b.addEventListener('click',()=>answerQuery(b.dataset.query))); $('view-mode').addEventListener('change',e=>applyViewMode(e.target.value)); $('scenario-select').addEventListener('change',e=>{engine.setScenario(e.target.value);toast('เปลี่ยนสถานการณ์จำลอง',data.scenarios[e.target.value].label,'warning');render()}); $('pause-button').addEventListener('click',()=>{engine.togglePause();render()});$('clear-events').addEventListener('click',()=>{engine.clearEvents();render()});$('run-validation').addEventListener('click',()=>{latestValidationRun=engine.runValidation();toast('Scenario Test Runner complete',`${latestValidationRun.passed}/${latestValidationRun.total} mock cases passed`);render()});$('run-failsafe').addEventListener('click',()=>{latestFailSafeRun=engine.runFailSafeDrill();toast('Fail-safe Drill complete','ตรวจ logic ระดับข้อมูลแล้ว, edge hardware ยังต้องทดสอบแยก');render()});$('export-incident').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(engine.incidentEvidence(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`gasguard-incident-evidence-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),200);toast('ดาวน์โหลด Incident Evidence แล้ว','ไฟล์มี reading, analysis, explanation และ recent events')});$('settings-form').addEventListener('submit',e=>{e.preventDefault();providers.reset();engine.saveSource({mode:$('source-mode').value,restUrl:$('rest-url').value.trim(),mqttUrl:$('mqtt-url').value.trim(),topic:$('mqtt-topic').value.trim()});toast('บันทึกการตั้งค่า','เก็บใน local browser storage แล้ว');render()});$('export-data').addEventListener('click',()=>{const blob=new Blob([engine.exportData()],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`gasguard-draft-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),200);});
  applyViewMode((()=>{try{return localStorage.getItem(VIEW_KEY)||'owner'}catch(e){return 'owner'}})());render();setInterval(async()=>{const before=engine.analysis.safety, after=await providers.tick();render();if(before!==after.safety&&after.safety!=='safe')toast('Safety state changed',statusText(after.safety),after.safety==='critical'?'critical':'warning')},2000);
})();
