(function(){'use strict';
  const KEY='gasguard-v2-service-workflow', VERSION='service-workflow-v0.1';
  const safeLoad=()=>{try{const v=JSON.parse(localStorage.getItem(KEY));return v&&typeof v==='object'?v:{version:VERSION,requests:[],tasks:[],verifications:[],reports:[],warning:null};}catch(e){return{version:VERSION,requests:[],tasks:[],verifications:[],reports:[],warning:'ข้อมูล workflow เดิมอ่านไม่ได้ จึงเริ่มในสถานะกู้คืนได้'}}};
  const state=safeLoad(), save=()=>{try{localStorage.setItem(KEY,JSON.stringify({...state,version:VERSION}));return true}catch(e){state.warning='พื้นที่เก็บข้อมูลในเบราว์เซอร์ไม่เพียงพอ';return false}};
  const id=(prefix)=>`${prefix}-${Date.now()}-${Math.random().toString(16).slice(2,8)}`;
  const now=()=>new Date().toISOString(), open=['submitted','acknowledged','scheduled','in_progress','awaiting_verification','unable_to_complete'];
  const history=(request,action,next,role)=>request.history.push({timestamp:now(),action,previousStatus:request.status,newStatus:next,actorRole:role});
  const incident=(incidentId)=>window.GasGuardEngine?.state.events.find(e=>(e.eventId||e.id)===incidentId)||null;
  function create(input={}){const related=incident(input.incidentId), existing=related&&state.requests.find(r=>r.incidentId===input.incidentId&&open.includes(r.status));if(existing)return{request:existing,duplicate:true};const at=now(),request={requestId:id('req'),siteId:input.siteId??related?.siteId??null,incidentId:input.incidentId??null,zoneId:input.zoneId??related?.zoneId??null,deviceIds:input.deviceIds??related?.deviceIds??[],source:related?.source||'simulation',requestType:input.requestType||'inspection',title:input.title||'ขอให้ตรวจสอบระบบ',description:input.description||null,priority:input.priority||'normal',status:'submitted',submittedAt:at,acknowledgedAt:null,scheduledAt:null,startedAt:null,awaitingVerificationAt:null,completedAt:null,cancelledAt:null,requester:'ผู้ใช้งานตัวอย่าง',assignedTechnician:null,contactPreference:input.contactPreference||'Demo contact',technicianNotes:[],relatedMaintenanceTaskIds:[],serviceReportId:null,history:[],createdFrom:input.incidentId?'incident':'general',mock:true};history(request,'submitted','submitted','general');state.requests.unshift(request);save();return{request,duplicate:false};}
  const transitions={submitted:['acknowledged','cancelled'],acknowledged:['scheduled','in_progress','cancelled'],scheduled:['in_progress','cancelled'],in_progress:['awaiting_verification','unable_to_complete'],awaiting_verification:['completed','in_progress','unable_to_complete'],completed:[],cancelled:[],unable_to_complete:['in_progress']};
  function transition(requestId,next,role='technician'){const r=state.requests.find(x=>x.requestId===requestId);if(!r||!transitions[r.status]?.includes(next))return false;if(next==='completed'){const v=state.verifications.find(x=>x.requestId===requestId);if(!v||v.result!=='passed')return false;}history(r,`status_${next}`,next,role);r.status=next;const at=now();if(next==='acknowledged')r.acknowledgedAt=at;if(next==='scheduled')r.scheduledAt=at;if(next==='in_progress'){r.startedAt=r.startedAt||at;r.assignedTechnician=r.assignedTechnician||'ช่างตัวอย่าง';}if(next==='awaiting_verification')r.awaitingVerificationAt=at;if(next==='completed')r.completedAt=at;if(next==='cancelled')r.cancelledAt=at;save();return true;}
  function note(requestId,text){const r=state.requests.find(x=>x.requestId===requestId);if(!r)return false;r.technicianNotes.push({at:now(),text:String(text||'').trim()||null,actorRole:'technician',mock:true});save();return true;}
  function task(requestId,input={}){const r=state.requests.find(x=>x.requestId===requestId);if(!r)return null;const t={maintenanceTaskId:id('mt'),requestId,incidentId:r.incidentId,siteId:r.siteId,zoneId:r.zoneId,deviceId:input.deviceId||r.deviceIds[0]||null,actionType:input.actionType||'inspect_device',description:input.description||null,status:'open',performedBy:'ช่างตัวอย่าง',startedAt:now(),completedAt:null,result:null,notes:null,evidence:[],mock:true};state.tasks.unshift(t);r.relatedMaintenanceTaskIds.push(t.maintenanceTaskId);save();return t;}
  function verify(requestId,input={}){const r=state.requests.find(x=>x.requestId===requestId);if(!r)return null;const v={verificationId:id('ver'),requestId,incidentId:r.incidentId,performedAt:now(),performedBy:'ช่างตัวอย่าง',testType:input.testType||'simulation_follow_up',expectedResult:'รอเกณฑ์จากคู่มือหรือผล Validation',observedResult:input.observedResult||null,result:input.result||'unable_to_test',evidence:[],notes:input.notes||null,mock:true};state.verifications=[v,...state.verifications.filter(x=>x.requestId!==requestId)];if(v.result==='passed')state.tasks.filter(t=>t.requestId===requestId&&t.status!=='completed').forEach(t=>{t.status='completed';t.completedAt=v.performedAt;t.result='mock verification passed'});save();return v;}
  function report(requestId){const r=state.requests.find(x=>x.requestId===requestId);if(!r)return null;const existing=state.reports.find(x=>x.requestId===requestId);if(existing)return existing;const i=incident(r.incidentId),v=state.verifications.find(x=>x.requestId===requestId),report={reportId:id('rpt'),requestId,incidentId:r.incidentId,siteId:r.siteId,zoneId:r.zoneId,deviceIds:r.deviceIds,reportedIssue:r.description||r.title,incidentSummary:i?i.detail:'ยังไม่มีข้อมูล',diagnosticSummary:r.technicianNotes.at(-1)?.text||'ยังไม่มีข้อมูล',actionsPerformed:r.relatedMaintenanceTaskIds,partsReplaced:[],verificationResult:v?.result||null,detectionStatusAtCompletion:i?.lifecycleStatus||null,technicianWorkflowResult:r.status,createdAt:now(),completedAt:r.completedAt||null,nextAction:r.status==='completed'?'ไม่มีข้อมูลเพิ่มเติม':'ติดตามงานบริการต่อ',technicianIdentity:'ช่างตัวอย่าง',evidenceReferences:[],mock:true};state.reports.unshift(report);r.serviceReportId=report.reportId;save();return report;}
  const protectedIncidentIds=()=>new Set([...state.requests.filter(r=>open.includes(r.status)).map(r=>r.incidentId),...state.tasks.filter(t=>t.status!=='completed').map(t=>t.incidentId)].filter(Boolean));
  window.GasGuardService={state,KEY,VERSION,create,transition,note,task,verify,report,protectedIncidentIds,save};
})();
